### ISSUE TITLE
Updating cluster instance type forces cluster replacement

### ISSUE THREAD

**Issue by canidam** [angelabad/terraform-aws-msk-cluster#12]
**Version:**
```
  source  = "angelabad/msk-cluster/aws"
  version = "0.3.4"
```

Changing an existing cluster _instance type_ forces **cluster replacement**

```
-/+ resource "aws_msk_cluster" "this" {
            ...
            ebs_volume_size = 1000
          ~ instance_type   = "kafka.m5.large" -> "kafka.m5.xlarge" # forces replacement
            security_groups = [
            ...
```

While this isn't a constraint; it is possible to modify an existing cluster broker's instance type in-place.

This is a real issue when managing long term clusters. Any chance fixing it?

**Comment by canidam** [comment]
on a second thought, it might be an issue with the aws provider rather than this module, right?

**Comment by angelabad** [comment]
Closed
