### ISSUE TITLE
sasl_scram_secret is now in the aws provider

### ISSUE THREAD

**Issue by jurgenweber** [angelabad/terraform-aws-msk-cluster#5]
https://github.com/hashicorp/terraform-provider-aws/pull/15302

add support to this module

**Comment by rogercoll** [comment]
Is there any update or progress in that?

Many thanks!

**Comment by angelabad** [comment]
Hi @jurgenweber, nowadays provider is buggy, so Im wating for this:

* https://github.com/hashicorp/terraform-provider-aws/issues/20956

Thanks in advance!

**Comment by angelabad** [comment]
Hi, closed in https://github.com/angelabad/terraform-aws-msk-cluster/pull/21

Bye
